Repository 4N-backend/fn_ai, pull requests merged in 2025-03, with the labels that each got.

#2 Feature/#1 MSA 초기세팅(API Gateway, Eureka Server & Client, Config Server)
  com.fn.ai.company/src/main/resources/application.properties
  com.fn.ai.company/src/main/resources/application.yml
  com.fn.ai.config/build.gradle
  com.fn.ai.config/src/main/java/com/fn/ai/config/ConfigApplication.java
  com.fn.ai.config/src/main/resources/application.properties
  com.fn.ai.config/src/main/resources/application.yml
  com.fn.ai.config/src/main/resources/config-repo/company-service.yml
  com.fn.ai.config/src/main/resources/config-repo/delivery-service.yml
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.config/src/main/resources/config-repo/hub-service.yml
  com.fn.ai.config/src/main/resources/config-repo/notification-service.yml
  com.fn.ai.config/src/main/resources/config-repo/order-service.yml
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.config/src/main/resources/config-repo/user-service.yml
  com.fn.ai.delivery/src/main/resources/application.properties
  com.fn.ai.delivery/src/main/resources/application.yml
  com.fn.ai.eureka/src/main/java/com/fn/ai/eureka/EurekaApplication.java
  com.fn.ai.eureka/src/main/resources/application.properties
  com.fn.ai.eureka/src/main/resources/application.yml
  com.fn.ai.gateway/build.gradle
  com.fn.ai.gateway/src/main/resources/application.properties
  com.fn.ai.gateway/src/main/resources/application.yml
  com.fn.ai.hub/src/main/resources/application.properties
  com.fn.ai.hub/src/main/resources/application.yml
  com.fn.ai.notification/src/main/resources/application.properties
  com.fn.ai.notification/src/main/resources/application.yml
  com.fn.ai.order/src/main/resources/application.properties
  com.fn.ai.order/src/main/resources/application.yml
  com.fn.ai.product/src/main/resources/application.properties
  com.fn.ai.product/src/main/resources/application.yml
  com.fn.ai.user/src/main/resources/application.properties
  com.fn.ai.user/src/main/resources/application.yml
  docker-compose.yml
Labels: ⚙️ setting

#6 add root module
  .gitattributes
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: ✨feat

#9 build: 공통 모듈 세팅
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/misc.xml
  .idea/modules.xml
  com.fn.ai.common/.gitattributes
  com.fn.ai.common/.gitignore
  com.fn.ai.common/build.gradle
  com.fn.ai.common/gradle/wrapper/gradle-wrapper.jar
  com.fn.ai.common/gradle/wrapper/gradle-wrapper.properties
  com.fn.ai.common/gradlew
  com.fn.ai.common/gradlew.bat
  com.fn.ai.common/settings.gradle
  com.fn.ai.common/src/main/java/com/fn/ai/common/CommonApplication.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/GlobalExceptionHandler.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/AutoConfig.java
  com.fn.ai.common/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports
  com.fn.ai.common/src/main/resources/application.properties
  com.fn.ai.common/src/test/java/com/fn/ai/common/CommonApplicationTests.java
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/controller/DeliveryController.java
  settings.gradle
Labels: ⚙️ setting

#11 feat: User, Slack 초기 세팅
  com.fn.ai.config/src/main/resources/config-repo/notification-service.yml
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/application/service/SlackService.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/model/SlackEntity.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/repository/SlackRepository.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/controller/SlackController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/UserService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/domain/model/DeliveryManagerEntity.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/domain/model/UserEntity.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/domain/repository/DeliveryManagerRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/domain/repository/UserRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/DeliveryManagerController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/UserController.java
Labels: ⚙️ setting

#10 Feature/#3 인증 인가 구현
  .idea/codeStyles/codeStyleConfig.xml
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/git_toolbox_blame.xml
  .idea/git_toolbox_prj.xml
  .idea/modules/auth.main.iml
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/AuthApplication.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/AuthService.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/client/UserClient.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/client/dto/UserRegisterRequestDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/client/dto/UserResponseDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/AuthController.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/dto/request/SignInRequestDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/dto/request/SignUpRequestDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/dto/response/SignInResponseDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/dto/response/SignUpResponseDto.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/UserDetailsImpl.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/UserDetailsServiceImpl.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/UserRoleEnum.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/WebSecurityConfig.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/jwt/JwtAuthenticationFilter.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/jwt/JwtAuthorizationFilter.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/jwt/JwtUtil.java
  com.fn.ai.auth/src/main/resources/application.yml
  com.fn.ai.auth/src/test/java/com/fn/ai/auth/AuthApplicationTests.java
  com.fn.ai.config/src/main/resources/config-repo/auth-service.yml
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.config/src/main/resources/config-repo/user-service.yml
  com.fn.ai.gateway/build.gradle
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPostFilter.java
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPreFilter.java
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/jwt/JwtUtil.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/User.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/UserRoleEnum.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/UserService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/UserRespository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/UserController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignInRequestDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignInResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignUpRequestDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignUpResponseDto.java
  init.sql
Labels: ✨feat, ⚙️ setting

#17 Feature/#16 commonresponse
  com.fn.ai.common/src/main/java/com/fn/ai/common/application/CommonResponse.java
  com.fn.ai.hub/build.gradle
Labels: ✨feat

#19 feat(18): 공통 에러 클래스 생성, commonresponse구조 변경
  com.fn.ai.common/src/main/java/com/fn/ai/common/GlobalExceptionHandler.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/application/CommonResponse.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/BaseException.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/GlobalExceptionHandler.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/code/CommonResponseCode.java
Labels: ✨feat

#23 Feature/#13 products crud
  com.fn.ai.auth/src/test/java/com/fn/ai/auth/AuthApplicationTests.java
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPostFilter.java
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPreFilter.java
  com.fn.ai.product/build.gradle
  com.fn.ai.product/src/main/java/com/fn/ai/product/ProductApplication.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/client/CompanyClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/client/HubClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/dto/CompanyResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/dto/HubResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/CompanyFeignClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/HubFeignClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/service/CompanyClientImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/service/HubClientImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/model/Product.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/model/repository/ProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/ProductContoller.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/request/ProductCreateRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/request/ProductCreateResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductUpdateRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductUpdateResponseDto.java
  com.fn.ai.product/src/main/resources/application.yml
  settings.gradle
Labels: bug, ✨feat, ⚙️ setting

#20 Feature/#12 Slack API 연동 기능 구현
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/application/service/SlackService.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/application/service/SlackServiceImpl.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/CustomException.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/ErrorType.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/GlobalExceptionHandler.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/ResponseDataDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/ResponseStatus.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/model/Slack.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/repository/SlackRepository.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/infrastructure/client/SlackApiClient.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/infrastructure/config/RestTemplateConfig.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/infrastructure/dto/response/SlackSendResponse.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/controller/SlackController.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/request/SlackCreateRequestDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/request/SlackUpdateRequestDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackDeleteResponseDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackResponseDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackUpdateResponseDto.java
  com.fn.ai.notification/src/main/resources/application.yml
Labels: ✨feat

#27 bug(25) : Common-moudle-debug
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/gradle.xml
  .idea/modules.xml
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/code/CommonResponseCode.java
  com.fn.ai.common/src/main/resources/application.properties
  com.fn.ai.common/src/main/resources/application.yml
  com.fn.ai.config/src/main/resources/config-repo/company-service.yml
  com.fn.ai.config/src/main/resources/config-repo/hub-service.yml
  com.fn.ai.config/src/main/resources/config-repo/notification-service.yml
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.config/src/main/resources/config-repo/user-service.yml
  com.fn.ai.hub/build.gradle
  docker-compose.yml
  init.sql
Labels: bug, ⚙️ setting

#31 feat: create-delivery
  com.fn.ai.config/src/main/resources/config-repo/delivery-service.yml
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/DeliveryApplication.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/HubClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/HubRouteRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/HubRouteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/dto/DeliveryCreateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/dto/DeliveryCreateResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubClientImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/db/JpaDeliveryRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/db/JpaDeliveryRouteRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/DeliveryRoute.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/repository/DeliveryRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/repository/DeliveryRouteRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/type/DeliveryStatus.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/DeliveryController.java
Labels: ✨feat

#28 Feature/#14 hub crud
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/misc.xml
  com.fn.ai.config/src/main/resources/config-repo/hub-service.yml
  com.fn.ai.hub/build.gradle
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/HubApplication.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/dto/request/HubCreateRequestDto.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/dto/request/HubUpdateRequestDto.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/dto/response/HubResponseDto.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/Hub.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/HubRoute.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/HubRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/HubRouteRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/vo/Address.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/vo/Distance.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/vo/Duration.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/vo/Location.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/vo/Name.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/HubRepositoryImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/HubRouteJpaRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/QuerydslConfig.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/jpa/HubJpaRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/resources/application.yml
Labels: ✨feat

#34 Feature/#24 order create
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.config/src/main/resources/config-repo/order-service.yml
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.order/build.gradle
  com.fn.ai.order/src/main/java/com/fn/ai/order/OrderApplication.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/client/CompanyClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/client/DeliveryClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/client/ProductClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/dto/CompanyRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/dto/CompanyResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/dto/DeliveryCreateRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/dto/DeliveryCreateResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/service/dto/ProductResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/CompanyFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/DeliveryFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/ProductFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/CompanyClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/DeliveryClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/ProductClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/db/JpaOrderRepository.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/model/Order.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/model/OrderItem.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/model/OrderRepository.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/OrderController.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderCreateRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderCreateResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderItemRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderItemResponseDto.java
  com.fn.ai.order/src/test/java/com/fn/ai/order/OrderApplicationTests.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/request/ProductCreateRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductUpdateRequestDto.java
Labels: ✨feat, ⚙️ setting

#36 refactor: create-delivery
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/DeliveryApplication.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/HubClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/HubRouteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/controller/DeliveryController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubClientImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/DeliveryRoute.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/repository/DeliveryRouteRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/vo/Address.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/vo/DeliverySequence.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/vo/Distance.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/vo/Duration.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/DeliveryController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryCreateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryCreateResponseDto.java
  com.fn.ai.delivery/src/test/java/com/fn/ai/delivery/DeliveryApplicationTests.java
Labels: 🔨refactor

#40 bug(39) : settings.gradle
  .idea/modules.xml
  com.fn.ai.common/settings.gradle
  com.fn.ai.company/build.gradle
  com.fn.ai.company/settings.gradle
  com.fn.ai.config/settings.gradle
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/settings.gradle
  com.fn.ai.eureka/settings.gradle
  com.fn.ai.gateway/settings.gradle
  com.fn.ai.hub/build.gradle
  com.fn.ai.hub/settings.gradle
  com.fn.ai.notification/build.gradle
  com.fn.ai.notification/settings.gradle
  com.fn.ai.order/build.gradle
  com.fn.ai.order/settings.gradle
  com.fn.ai.product/build.gradle
  com.fn.ai.product/settings.gradle
  com.fn.ai.user/build.gradle
  com.fn.ai.user/settings.gradle
  settings.gradle
Labels: bug

#42 refactor(41) : gitignore
  .gitignore
Labels: ⚙️ setting, 🔨refactor

#44 Feature/#43 setting add auth build gradle
  com.fn.ai.auth/.gitattributes
  com.fn.ai.auth/.gitignore
  com.fn.ai.auth/build.gradle
  com.fn.ai.auth/gradle/wrapper/gradle-wrapper.jar
  com.fn.ai.auth/gradle/wrapper/gradle-wrapper.properties
  com.fn.ai.auth/gradlew
  com.fn.ai.auth/gradlew.bat
  com.fn.ai.auth/settings.gradle
Labels: ⚙️ setting

#38 feat: delivery read one, read all, update, delete
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/repository/DeliveryRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/type/DeliveryStatus.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/DeliveryController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryDetailsResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliverySummaryResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryUpdateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryUpdateResponseDto.java
Labels: ✨feat

#45 Feature/#21 create base entity
  .idea/modules.xml
  com.fn.ai.common/build.gradle
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/auditor/CustomAuditorAware.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/auditor/JpaAuditorAwareConfig.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/UserContext.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/UserContextHolder.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/entity/BaseEntity.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
Labels: ✨feat

#49 Feature/#48 common module order product
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/UserContext.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/UserContextHolder.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/UserRoleEnum.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/annotation/CurrentUserInfo.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/annotation/UserHeaderArgumentResolver.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/context/annotation/WebConfig.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/code/CommonResponseCode.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPreFilter.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/model/Order.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/model/OrderItem.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/OrderController.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/dto/CompanyResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/dto/HubResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/model/Product.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/ProductContoller.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/User.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/UserRoleEnum.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/UserService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/User.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/UserRespository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignInResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignUpRequestDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserSignUpResponseDto.java
Labels: ✨feat, 🔨refactor

#56 feat: delivery depart/arrive/complete API
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/HubRouteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/exception/AlreadyCompletedDelivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/exception/DeliveryNotFoundException.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/exception/DeliverySequenceOutOfRangeException.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/db/JpaDeliveryRouteRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/DeliveryRoute.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/repository/DeliveryRouteRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/type/DeliveryRouteStatus.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/vo/DeliverySequence.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/DeliveryController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryArriveHubRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryArriveHubResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryCompleteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryCreateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryDepartHubResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/dto/DeliveryDetailsResponseDto.java
Labels: ✨feat, 🔨refactor

#61 Refactor/#59 order compensation transactions
  com.fn.ai.common/build.gradle
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/FeignConfig.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/client/ProductClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/CompanyRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/DeliveryCreateRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/ProductResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/ProductStockRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/ProductFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/ProductClientImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/dto/ProductRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepositoryCustom.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepositoryCustomImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/model/repository/ProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/ProductContoller.java
  init.sql
Labels: ✨feat, 🔨refactor

#65 build: notification-server gateway uri 변경, 라이브러리 임시 제거
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.notification/build.gradle
Labels: ⚙️ setting

#66 feat(30) : company-crud
  com.fn.ai.company/build.gradle
  com.fn.ai.company/src/main/java/com/fn/ai/company/CompanyApplication.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/CompanyService.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/CompanyServiceImpl.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/HubClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/UserClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/request/CompanyCreateRequestDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/request/CompanyUpdateRequestDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/CompanyCreateResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/CompanyGetHubResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/CompanyResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/CompanyUpdateResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/HubInfoResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/response/UserInfoResponseDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/domain/Company.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/domain/CompanyType.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/domain/repository/CompanyRepository.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/domain/vo/Address.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/domain/vo/Name.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/infrastructure/CompanyRepositoryImpl.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/infrastructure/config/QuerydslConfig.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/infrastructure/jpa/CompanyJpaRepository.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/presentation/CompanyController.java
  com.fn.ai.config/src/main/resources/config-repo/company-service.yml
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/UserController.java
Labels: ✨feat

#69 Feature/#60 swagger
  .idea/compiler.xml
  .idea/modules.xml
  build.gradle
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/client/UserClient.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/GlobalExceptionHandler.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/MutableHttpServletRequest.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/SwaggerHeaderMockFilter.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.company/build.gradle
  com.fn.ai.company/src/main/java/com/fn/ai/company/presentation/CompanyController.java
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/config/FilterConfig.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/DeliveryController.java
  com.fn.ai.gateway/build.gradle
  com.fn.ai.gateway/src/main/resources/application.yml
  com.fn.ai.hub/build.gradle
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/exception/HubNotFoundException.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/FilterConfig.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
  com.fn.ai.hub/src/main/resources/application.yml
  com.fn.ai.notification/build.gradle
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/GlobalExceptionHandler.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/infrastructure/config/FilterConfig.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/controller/SlackController.java
  com.fn.ai.notification/src/main/resources/application.yml
  com.fn.ai.order/build.gradle
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/config/FilterConfig.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/OrderController.java
  com.fn.ai.product/build.gradle
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/config/FilterConfig.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/ProductContoller.java
  com.fn.ai.user/build.gradle
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/UserServiceImpl.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/config/FilterConfig.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/vo/Username.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/DeliveryManagerController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/UserController.java
  com.fn.ai.user/src/main/resources/application.yml
Labels: ✨feat

#71 Feature/#67 product test
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/DeliveryCreateRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/CompanyFeignClient.java
  com.fn.ai.product/build.gradle
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/model/repository/ProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/request/ProductCreateRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductSearchResponseDto.java
  com.fn.ai.product/src/main/resources/application-test.yml
  com.fn.ai.product/src/test/java/com/fn/ai/product/ProductApplicationTests.java
  com.fn.ai.product/src/test/java/com/fn/ai/product/application/service/ProductServiceTest.java
  com.fn.ai.product/src/test/java/com/fn/ai/product/common/UnitTestSupport.java
  com.fn.ai.product/src/test/java/com/fn/ai/product/config/TearDownExecutor.java
Labels: ✅test

#72 feat: delivery manager assign API
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryAssignService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/DeliveryManagerClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/DeliveryManagerAssignRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/DeliveryManagerAssignResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/DeliveryManagerClientImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/DeliveryManagerFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/DeliveryRoute.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/DeliveryExternalController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryArriveHubRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryArriveHubResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryAssignResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryCompleteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryDepartHubResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryDetailsResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliverySummaryResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryUpdateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryUpdateResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/internal/DeliveryInternalController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/internal/dto/DeliveryCreateRequestDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/internal/dto/DeliveryCreateResponseDto.java
  com.fn.ai.hub/src/main/resources/application.yml
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerServiceImpl.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/jpa/JpaDeliveryManagerRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/DeliveryManagerController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerAssignRequestDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerAssignResponseDto.java
Labels: ✨feat

#73 refactor: 주문-배송-허브 테스트 및 리팩토링
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/FeignConfig.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/HubClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/UserClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/infrastructure/config/FilterConfig.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/presentation/CompanyController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryServiceImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/HubClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/HubRouteResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubClientImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/client/CompanyClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/CompanyResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/CompanyFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/DeliveryFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/ProductFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/CompanyClientImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/CompanyFeignClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/HubFeignClient.java
  com.fn.ai.user/src/main/resources/application.yml
Labels: 🔨refactor, ✅test

#75 refactor: springdoc-openapi-starter-webmvc-ui version from 2.2.0 to 2.7.0
  com.fn.ai.auth/build.gradle
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/GlobalExceptionHandler.java
  com.fn.ai.company/build.gradle
  com.fn.ai.delivery/build.gradle
  com.fn.ai.gateway/build.gradle
  com.fn.ai.hub/build.gradle
  com.fn.ai.notification/build.gradle
  com.fn.ai.order/build.gradle
  com.fn.ai.product/build.gradle
  com.fn.ai.user/build.gradle
Labels: 🔨refactor

#78 test: 상품 재고 동시성 이슈 테스트
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/test/java/com/fn/ai/product/application/service/ProductServiceTest.java
Labels: ✅test

#80 refactor: restore request mapping
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/application/client/UserClient.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/entity/BaseEntity.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/MutableHttpServletRequest.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/CompanyServiceImpl.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/HubClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/UserClient.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/application/dto/request/CompanyCreateRequestDto.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/presentation/CompanyController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/HubFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/DeliveryExternalController.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/internal/DeliveryInternalController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/MapApiService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/HubRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/HubRouteRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/HubRouteRepositoryImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/FilterConfig.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/RestTemplateConfig.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/application/service/SlackService.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/application/service/SlackServiceImpl.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/common/GlobalExceptionHandler.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/model/Slack.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/domain/repository/SlackRepository.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/infrastructure/client/SlackApiClient.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/controller/SlackController.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackDeleteResponseDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackResponseDto.java
  com.fn.ai.notification/src/main/java/com/fn/ai/notification/slack/presentation/dto/response/SlackUpdateResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/CompanyFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/DeliveryFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/ProductFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/OrderController.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/CompanyFeignClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/HubFeignClient.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/ProductContoller.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerServiceImpl.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/UserService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/UserServiceImpl.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/jpa/JpaDeliveryManagerRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/jpa/JpaUserRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/DeliveryManager.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/User.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/repository/DeliveryManagerRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/repository/UserRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/DeliveryManagerController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/UserController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerInfoResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/UserInfoResponseDto.java
Labels: 🔨refactor

#81 refactor: common swagger refactor
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
Labels: 🔨refactor

#85 refactor: integration refactor
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.company/src/main/java/com/fn/ai/company/infrastructure/config/FilterConfig.java
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.gateway/src/main/resources/application.yml
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/dto/DeliveryCreateRequestDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepositoryCustomImpl.java
Labels: 🔨refactor

#87 feat(86): swagger-ui
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/presentation/AuthController.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/CorsConfig.java
  com.fn.ai.auth/src/main/java/com/fn/ai/auth/security/WebSecurityConfig.java
  com.fn.ai.auth/src/main/resources/application.yml
  com.fn.ai.common/build.gradle
  com.fn.ai.common/src/main/java/com/fn/ai/common/config/SwaggerConfig.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/filter/UserContextFilter.java
  com.fn.ai.gateway/src/main/java/com/fn/ai/gateway/filter/CustomPreFilter.java
  com.fn.ai.gateway/src/main/resources/application.yml
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
Labels: ✨feat

#89 refactor(88) : hub-refactor
  com.fn.ai.config/src/main/resources/config-repo/hub-service.yml
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/CalcHubRouteRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/CalcHubRouteRepositoryImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
Labels: 🔨refactor

#91 refactor: delivery manager assign & Redis distribute lock
  com.fn.ai.common/src/main/java/com/fn/ai/common/application/CommonResponse.java
  com.fn.ai.common/src/main/java/com/fn/ai/common/exception/GlobalExceptionHandler.java
  com.fn.ai.config/src/main/resources/config-repo/gateway-service.yml
  com.fn.ai.delivery/build.gradle
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/DeliveryAssignService.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/DeliveryManagerClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/application/client/dto/DeliveryManagerNextSequenceResponseDto.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/exception/AlreadyCompletedDeliveryException.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/DeliveryManagerClientImpl.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/DeliveryManagerFeignClient.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/config/RedisConfig.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/config/RedissonConfig.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/redis/CacheRepository.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/redis/DistributeLock.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/redis/DistributeLockAspect.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/redis/exception/RedissonLockAcquireFailedException.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/model/Delivery.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/presentation/external/dto/DeliveryAssignResponseDto.java
  com.fn.ai.user/build.gradle
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerService.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/application/service/DeliveryManagerServiceImpl.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/config/RedisConfig.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/config/RedissonConfig.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/jpa/JpaDeliveryManagerRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/redis/CacheRepository.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/redis/DistributeLock.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/redis/DistributeLockAspect.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/redis/exception/RedissonLockAcquireFailedException.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/model/DeliveryManager.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/controller/DeliveryManagerController.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerAssignResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerInfoResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerNextSequenceResponseDto.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/presentation/dto/DeliveryManagerResponseDto.java
  docker-compose.yml
Labels: ✨feat, 🔨refactor

#95 refactor: Order, Product refactor
  com.fn.ai.order/src/main/java/com/fn/ai/order/application/OrderService.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/domain/OrderSortType.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/domain/model/Order.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/domain/model/OrderItem.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/domain/repository/OrderRepository.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/CompanyClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/CompanyFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/DeliveryClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/DeliveryFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/ProductClientImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/client/ProductFeignClient.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/config/QueryDslConfig.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/db/JpaOrderRepository.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/db/JpaOrderRepositoryCustom.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/infrastructure/db/JpaOrderRepositoryCustomImpl.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/OrderController.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderCreateResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderItemResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderSearchRequestDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderSearchResponseDto.java
  com.fn.ai.order/src/main/java/com/fn/ai/order/presentation/dto/OrderUpdateResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/application/service/ProductService.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/domain/ProductSortType.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/domain/model/Product.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/domain/repository/ProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/config/QueryDslConfig.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepository.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/infrastructure/db/JpaProductRepositoryCustomImpl.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/request/ProductCreateResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductSearchResponseDto.java
  com.fn.ai.product/src/main/java/com/fn/ai/product/presentation/dto/response/ProductUpdateResponseDto.java
  com.fn.ai.product/src/test/java/com/fn/ai/product/application/service/ProductServiceTest.java
Labels: 🔨refactor

#92 refactor(88) : hub-refactor
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteService.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/CalcHubRouteDistance.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/domain/repository/HubRouteRepository.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/HubRepositoryImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/HubRouteRepositoryImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubController.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/presentation/HubRouteController.java
Labels: bug, 🔨refactor

#96 feat(93): hub-redis
  com.fn.ai.hub/build.gradle
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/HubApplication.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/application/HubRouteServiceImpl.java
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/RedisConfig.java
Labels: ✨feat

#98 Feature/#97 docker container
  .gitignore
  build.gradle
  com.fn.ai.auth/Dockerfile
  com.fn.ai.auth/src/main/resources/application.yml
  com.fn.ai.common/build.gradle
  com.fn.ai.company/Dockerfile
  com.fn.ai.company/src/main/resources/application.yml
  com.fn.ai.config/Dockerfile
  com.fn.ai.config/src/main/resources/application.yml
  com.fn.ai.config/src/main/resources/config-repo/company-service.yml
  com.fn.ai.config/src/main/resources/config-repo/delivery-service.yml
  com.fn.ai.config/src/main/resources/config-repo/hub-service.yml
  com.fn.ai.config/src/main/resources/config-repo/notification-service.yml
  com.fn.ai.config/src/main/resources/config-repo/order-service.yml
  com.fn.ai.config/src/main/resources/config-repo/product-service.yml
  com.fn.ai.config/src/main/resources/config-repo/user-service.yml
  com.fn.ai.delivery/Dockerfile
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/config/RedisConfig.java
  com.fn.ai.delivery/src/main/java/com/fn/ai/delivery/infrastructure/config/RedissonConfig.java
  com.fn.ai.delivery/src/main/resources/application.yml
  com.fn.ai.eureka/Dockerfile
  com.fn.ai.eureka/src/main/resources/application.yml
  com.fn.ai.gateway/Dockerfile
  com.fn.ai.gateway/src/main/resources/application.yml
  com.fn.ai.hub/Dockerfile
  com.fn.ai.hub/build.gradle
  com.fn.ai.hub/src/main/java/com/fn/ai/hub/infrastructure/config/RedisConfig.java
  com.fn.ai.hub/src/main/resources/application.yml
  com.fn.ai.notification/Dockerfile
  com.fn.ai.notification/src/main/resources/application.yml
  com.fn.ai.order/Dockerfile
  com.fn.ai.order/src/main/resources/application.yml
  com.fn.ai.product/Dockerfile
  com.fn.ai.product/src/main/resources/application.yml
  com.fn.ai.user/Dockerfile
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/config/RedisConfig.java
  com.fn.ai.user/src/main/java/com/fn/ai/user/infrastructure/config/RedissonConfig.java
  com.fn.ai.user/src/main/resources/application.yml
  docker-compose.yml
Labels: ✨feat
